#   Copyright (C) 2002 Free Software Foundation, Inc.
#   
#   Written by:	Manuel Guesdon <mguesdon@orange-concept.Com>
#   Date: 		Nov 2002
#   
#   This file is part of the GNUstep Web Library.
#   
#   This library is free software; you can redistribute it and/or
#   modify it under the terms of the GNU Library General Public
#   License as published by the Free Software Foundation; either
#   version 2 of the License, or (at your option) any later version.
#   
#   This library is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#   Library General Public License for more details.
#   
#   You should have received a copy of the GNU Library General Public
#   License along with this library; if not, write to the Free
#   Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

#
#   Makefile.preamble
#
#   Project specific makefile variables, and additional
#
#   Do not put any Makefile rules in this file, instead they should
#   be put into Makefile.postamble.
#

#
# Flags dealing with compiling and linking
#

# Additional flags to pass to the preprocessor
ADDITIONAL_CPPFLAGS = 

# Additional flags to pass to the Objective-C compiler
ADDITIONAL_OBJCFLAGS = 

# Additional flags to pass to the C compiler
ADDITIONAL_CFLAGS =  

# Additional flags to pass to the Objective-C compiler
#new
ifeq ($(GDL2), yes)
        ADDITIONAL_OBJCFLAGS = -DUSE_BUILTIN -DGDL2
else
        ADDITIONAL_OBJCFLAGS = -DUSE_BUILTIN
endif

# Additional include directories the compiler should search
ADDITIONAL_INCLUDE_DIRS =  -I$(GNUSTEP_SYSTEM_ROOT)/db -I../..

# Additional LDFLAGS to pass to the linker
ifeq ($(debug), yes)
	ADDITIONAL_LDFLAGS = -lGSWeb -lGSANTLR_d -lgnustep-db2_d -lgnustep-db2control_d
else
	ADDITIONAL_LDFLAGS = -lGSWeb -lGSANTLR -lgnustep-db2 -lgnustep-db2control
endif

ifeq ($(LIBWRAP), yes)
	ADDITIONAL_OBJCFLAGS := $(ADDITIONAL_OBJCFLAGS) -DHAVE_LIBWRAP
	ADDITIONAL_LDFLAGS := $(ADDITIONAL_LDFLAGS) -lwrap
endif

#-lgnustep-xraw

# Additional library directories the linker should search
ADDITIONAL_LIB_DIRS = 

#
# Flags dealing with installing and uninstalling
#

# Additional directories to be created during installation
ADDITIONAL_INSTALL_DIRS =
